# Generated by Django 5.1.3 on 2025-02-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_description',
            field=models.TextField(default=200),
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipe_name',
            field=models.CharField(default=100, max_length=100),
        ),
    ]
